name: Java Build and Test with Gradle

on:
  push:
    branches:
      - master # Change this to your main branch name

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build
      - name: Run Test with Gradle Wrapper
        run: ./gradlew test