# This is a GitHub Actions workflow to build and test a Java project using Gradle.
# It is triggered by pushes to the master branch.

on:
  push:
    branches:
      - master # Change this to your main branch name

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the project's source code from the repository.
      - name: Checkout project sources
        uses: actions/checkout@v3

      # Step 2: Set up the Gradle build tool on the runner.
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      # Step 3: Run the Gradle build using the Gradle Wrapper.
      - name: Run build with Gradle Wrapper
        run: ./gradlew build

      # Step 4: Run tests using the Gradle Wrapper.
      - name: Run Test with Gradle Wrapper
        run: ./gradlew test

      # Step 5: Publish JUnit-style test reports, even if the previous steps fail.
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

      # Step 6: Set up Docker
      - name: Set up Docker
        uses: docker/setup-action@v2

      # Step 7: Build and run your Docker container (replace with your Docker build commands)
      - name: Build and Run Docker Container
        run: |
          docker build -t my-docker-image .
          docker run my-docker-image
